# ASSIGNMENT-14: NUMPY

## SRABANI KHUNTIA, 24BCSB03
## GROUP-E1, ROLL NO:7

#### 1. Write a code to convert a 1D array to a 2D array with 2 rows.

In [8]:
import numpy as np
arr_1d = np.array([1, 2, 3, 4, 5, 6])
arr_2d = arr_1d.reshape(2, -1)
print("1D Array:", arr_1d)
print("2D Array (2 rows):\n", arr_2d)

1D Array: [1 2 3 4 5 6]
2D Array (2 rows):
 [[1 2 3]
 [4 5 6]]


#### 2. Create a 1D array filled with zeros and another filled with ones

In [11]:
zeros_array = np.zeros(5)
ones_array = np.ones(5, dtype=int) 
print("Zeros Array:", zeros_array)
print("Ones Array:", ones_array)

Zeros Array: [0. 0. 0. 0. 0.]
Ones Array: [1 1 1 1 1]


#### 3. Create a 1D array of 10 evenly spaced values between 5 and 50

In [14]:
spaced_array = np.linspace(5, 50, 10, dtype=int) #both limits are inclusive
print("Evenly Spaced Array:\n", spaced_array)

Evenly Spaced Array:
 [ 5 10 15 20 25 30 35 40 45 50]


#### 4. Convert a Python list into a NumPy arraY

In [15]:
python_list = [10, 20, 30, 40, 50]
numpy_array = np.array(python_list)
print("Python List:", type(python_list), python_list)
print("NumPy Array:", type(numpy_array), numpy_array)

Python List: <class 'list'> [10, 20, 30, 40, 50]
NumPy Array: <class 'numpy.ndarray'> [10 20 30 40 50]


#### 5. Create a 3×3 identity matrix

In [21]:
identity_matrix = np.eye(3)
print("3x3 Identity Matrix:\n", identity_matrix)

3x3 Identity Matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 6. Create a 4×4 array and extract its first row and last column

In [22]:
matrix_4x4 = np.arange(1, 17).reshape(4, 4)
first_row = matrix_4x4[0, :]
last_col = matrix_4x4[:, -1]
print("Original 4x4 Matrix:\n", matrix_4x4)
print("First Row:", first_row)
print("Last Column:", last_col)

Original 4x4 Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
First Row: [1 2 3 4]
Last Column: [ 4  8 12 16]


#### 7. Extract Odd Rows and Even Columns

In [23]:
matrix_5x5 = np.arange(1, 26).reshape(5, 5)
odd_rows_even_cols = matrix_5x5[1::2, 0::2]
print("Original Matrix:\n", matrix_5x5)
print("Odd Rows and Even Columns Extracted:\n", odd_rows_even_cols)

Original Matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
Odd Rows and Even Columns Extracted:
 [[ 6  8 10]
 [16 18 20]]


#### 8. Find the common items between two arrays

In [24]:
array_a = np.array([1, 2, 3, 4, 5])
array_b = np.array([4, 5, 6, 7, 8])
common_items = np.intersect1d(array_a, array_b)
print("Array A:", array_a)
print("Array B:", array_b)
print("Common Items:", common_items)

Array A: [1 2 3 4 5]
Array B: [4 5 6 7 8]
Common Items: [4 5]


#### 9. Write a code to extract all numbers from an array that are between 5 and 10 (inclusive)

In [25]:
array_c = np.array([1, 5, 7, 10, 12, 4, 8, 15])
filtered_array = array_c[(array_c >= 5) & (array_c <= 10)]
print("Original Array:", array_c)
print("Numbers between 5 and 10:", filtered_array)

Original Array: [ 1  5  7 10 12  4  8 15]
Numbers between 5 and 10: [ 5  7 10  8]


#### 10. Create a random 3×2 matrix and find its maximum and minimum values

In [30]:
random_matrix = np.random.rand(3, 2)
max_val = random_matrix.max()
min_val = random_matrix.min()
print("Random 3x2 Matrix:\n", random_matrix)
print("Maximum Value:", max_val)
print("Minimum Value:", min_val)

Random 3x2 Matrix:
 [[0.90916076 0.43197226]
 [0.33375325 0.53779037]
 [0.82416097 0.1248006 ]]
Maximum Value: 0.9091607563937218
Minimum Value: 0.12480059837533708


#### 11. Delete and Insert a Column in a NumPy Array

In [31]:
matrix_d = np.arange(1, 10).reshape(3, 3)
deleted_col_matrix = np.delete(matrix_d, 1, axis=1)
inserted_col_matrix = np.insert(deleted_col_matrix, 1, [99, 99, 99], axis=1)
print("Original Matrix:\n", matrix_d)
print("After Deleting Column 2:\n", deleted_col_matrix)
print("After Inserting New Column:\n", inserted_col_matrix)

Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
After Deleting Column 2:
 [[1 3]
 [4 6]
 [7 9]]
After Inserting New Column:
 [[ 1 99  3]
 [ 4 99  6]
 [ 7 99  9]]


#### 12. Swap column 1 and 2 in a 2D array

In [33]:
matrix_e = np.arange(1, 10).reshape(3, 3)
print("Original Matrix:\n", matrix_e)
matrix_e[:, [0, 1]] = matrix_e[:, [1, 0]] #[all rows, [columns to be swapped,]]
print("Matrix after swapping column 1 and 2:\n", matrix_e)

Original Matrix:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Matrix after swapping column 1 and 2:
 [[2 1 3]
 [5 4 6]
 [8 7 9]]


#### 13. Create a 3×3 array of random integers and sort it row-wise 

In [41]:
random_ints = np.random.randint(1, 50, (3, 3)) #same as ..(1, 50, 9).reshape(3, 3)
sorted_row_wise = np.sort(random_ints) #by default axis=1
print("Random Integers Matrix:\n", random_ints)
print("Sorted Row-wise:\n", sorted_row_wise)

Random Integers Matrix:
 [[49 14 19]
 [14 21  6]
 [47 41 24]]
Sorted Row-wise:
 [[14 19 49]
 [ 6 14 21]
 [24 41 47]]


#### 14.Create a 5×5 2D array with 1s on the border and 0s inside.

In [43]:
border_array = np.ones((5, 5), dtype=int)
border_array[1:-1, 1:-1] = 0
print("Border Array (1s outside, 0s inside):\n", border_array)

Border Array (1s outside, 0s inside):
 [[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 15.Sort the rows of a 2D array based on the values of the second column

In [44]:
unsorted_matrix = np.array([[9, 4, 2], [3, 1, 8], [6, 7, 5]])
sorted_by_2nd_col = unsorted_matrix[unsorted_matrix[:, 1].argsort()]
print("Original Matrix:\n", unsorted_matrix)
print("Sorted by the 2nd Column:\n", sorted_by_2nd_col)

Original Matrix:
 [[9 4 2]
 [3 1 8]
 [6 7 5]]
Sorted by the 2nd Column:
 [[3 1 8]
 [9 4 2]
 [6 7 5]]


#### 16.Count the number of occurrences of each unique element

In [45]:
duplicate_array = np.array([10, 20, 20, 30, 30, 30, 40])
unique_elements, counts = np.unique(duplicate_array, return_counts=True)
print("Array:", duplicate_array)
for item, count in zip(unique_elements, counts):
    print(f"Element {item} occurs {count} time(s)")

Array: [10 20 20 30 30 30 40]
Element 10 occurs 1 time(s)
Element 20 occurs 2 time(s)
Element 30 occurs 3 time(s)
Element 40 occurs 1 time(s)


#### 17.Transposing a matrix means flipping it over its diagonal.

In [46]:
matrix_to_transpose = np.array([[1, 2, 3], [4, 5, 6]])
transposed_matrix = matrix_to_transpose.T
print("Original Matrix:\n", matrix_to_transpose)
print("Transposed Matrix:\n", transposed_matrix)

Original Matrix:
 [[1 2 3]
 [4 5 6]]
Transposed Matrix:
 [[1 4]
 [2 5]
 [3 6]]


#### 18. Write a Python program using NumPy to:
#### 1. Create a 2D array for marks of 6 students in 4 subjects (user input)
#### 2. Compute total and average marks for each student
#### 3. Display students scoring above 70%
#### 4. Find the student with the second highest total marks
#### 5. Display subject-wise highest marks

In [50]:
# 1. User Input
marks_list = []
print("Enter marks for 6 students in 4 subjects (space-separated):")
for i in range(6):
    row = list(map(int, input(f"Student {i} marks: ").split()))
    marks_list.append(row)
marks_array = np.array(marks_list)

# 2. Compute total and average
totals = marks_array.sum(axis=1)
averages = marks_array.mean(axis=1)
print("\nTotals per student:", totals)
print("Averages per student:", averages)

# 3. Students scoring > 70%
above_70_indices = np.where(averages > 70)[0]
print("Students scoring above 70% (0-indexed):", above_70_indices)

# 4. Second highest total
sorted_totals = np.sort(np.unique(totals))
if len(sorted_totals) > 1:
    second_highest = sorted_totals[-2]
    second_highest_student = np.where(totals == second_highest)[0][0]
    print(f"Student {second_highest_student} has the second highest total: {second_highest}")
else:
    print("Not enough distinct totals to find a second highest.")

# 5. Subject-wise highest
subject_highest = marks_array.max(axis=0)
print("Subject-wise highest marks:", subject_highest)

Enter marks for 6 students in 4 subjects (space-separated):


Student 0 marks:  100 99 93 97
Student 1 marks:  81 89 91 84
Student 2 marks:  78 89 85 82
Student 3 marks:  100 100 99 98
Student 4 marks:  91 95 94 84
Student 5 marks:  89 86 84 96



Totals per student: [389 345 334 397 364 355]
Averages per student: [97.25 86.25 83.5  99.25 91.   88.75]
Students scoring above 70% (0-indexed): [0 1 2 3 4 5]
Student 0 has the second highest total: 389
Subject-wise highest marks: [100 100  99  98]


#### 19.Write a program to:
#### 1. Input two matrices
#### 2. Perform matrix addition, subtraction, and multiplication
#### 3. Find transpose of both matrices
#### 4. Compute determinant and inverse (if possible)
#### 5. Display results neatly

In [51]:
#1. 
print("Enter 2x2 Matrix A (row by row, space-separated):")
A = np.array([list(map(float, input("Row 1: ").split())), 
              list(map(float, input("Row 2: ").split()))])
print("Enter 2x2 Matrix B (row by row, space-separated):")
B = np.array([list(map(float, input("Row 1: ").split())), 
              list(map(float, input("Row 2: ").split()))])

#2. 
print("\nAddition:\n", A + B)
print("Subtraction:\n", A - B)
print("Multiplication (Dot Product):\n", np.dot(A, B))

#3. 
print("\nTranspose of A:\n", A.T)
print("Transpose of B:\n", B.T)

#4. 
print("\nDeterminant of A:", np.linalg.det(A))
print("Determinant of B:", np.linalg.det(B))
try:
    print("\nInverse of A:\n", np.linalg.inv(A))
except np.linalg.LinAlgError:
    print("\nMatrix A is singular, no inverse exists.")
try:
    print("Inverse of B:\n", np.linalg.inv(B))
except np.linalg.LinAlgError:
    print("Matrix B is singular, no inverse exists.")

Enter 2x2 Matrix A (row by row, space-separated):


Row 1:  7 8
Row 2:  1 5


Enter 2x2 Matrix B (row by row, space-separated):


Row 1:  5 3
Row 2:  6 12



Addition:
 [[12. 11.]
 [ 7. 17.]]
Subtraction:
 [[ 2.  5.]
 [-5. -7.]]
Multiplication (Dot Product):
 [[ 83. 117.]
 [ 35.  63.]]

Transpose of A:
 [[7. 1.]
 [8. 5.]]
Transpose of B:
 [[ 5.  6.]
 [ 3. 12.]]

Determinant of A: 27.0
Determinant of B: 41.999999999999986

Inverse of A:
 [[ 0.18518519 -0.2962963 ]
 [-0.03703704  0.25925926]]
Inverse of B:
 [[ 0.28571429 -0.07142857]
 [-0.14285714  0.11904762]]


#### 20.Write a program to:
#### 1. Create a 1D array of n elements (user input)
#### 2. Reshape it into a 2D array
#### 3. Flatten the array
#### 4. Sort elements in ascending and descending order
#### 5. Find maximum, minimum, and their indices

In [53]:
#1. 
n = int(input("Enter number of elements (must be an even number for a 2-row reshape): "))
elements = list(map(int, input(f"Enter {n} elements (space-separated): ").split()))
arr_1d = np.array(elements)

#2. 
rows = 2
cols = n // 2
arr_2d = arr_1d.reshape(rows, cols)
print("\nReshaped to 2D:\n", arr_2d)

#3. 
flattened = arr_2d.flatten()
print("Flattened array:\n", flattened)

#4. 
asc_sorted = np.sort(flattened)
desc_sorted = asc_sorted[::-1]
print("Ascending Sort:", asc_sorted)
print("Descending Sort:", desc_sorted)

#5. 
max_val = flattened.max()
min_val = flattened.min()
print(f"Max: {max_val} at index {np.argmax(flattened)}")
print(f"Min: {min_val} at index {np.argmin(flattened)}")

Enter number of elements (must be an even number for a 2-row reshape):  6
Enter 6 elements (space-separated):  7 8 2 6 4 5



Reshaped to 2D:
 [[7 8 2]
 [6 4 5]]
Flattened array:
 [7 8 2 6 4 5]
Ascending Sort: [2 4 5 6 7 8]
Descending Sort: [8 7 6 5 4 2]
Max: 8 at index 1
Min: 2 at index 2


#### 21.Write a program to:
#### 1. Create coefficient matrix A and constant matrix B(User Inputs)
#### 2. Solve the system using NumPy
#### 3. Verify solution by substituting back
#### 4. Handle singular matrix case

In [55]:
#### 1. 
print("Solving Ax = B for a 2-variable system.")
print("Enter Coefficient Matrix A (2x2):")
A = np.array([list(map(float, input("Row 1: ").split())), 
              list(map(float, input("Row 2: ").split()))])
print("Enter Constant Matrix B (2x1):")
B = np.array(list(map(float, input("Values: ").split())))

#2. 
try:
    x = np.linalg.solve(A, B)
    print("\nSolution (x, y):", x)
    
#3. 
    verification = np.allclose(np.dot(A, x), B)
    print("Solution verified by back substitution:", verification)
#4. 
except np.linalg.LinAlgError:
    print("\nSingular Matrix detected. The system has no unique solution.")

Solving Ax = B for a 2-variable system.
Enter Coefficient Matrix A (2x2):


Row 1:  7 8
Row 2:  4 5


Enter Constant Matrix B (2x1):


Values:  4 8



Solution (x, y): [-14.66666667  13.33333333]
Solution verified by back substitution: True


#### 22.Write a program to:
#### 1. Create a 5×5 array
#### 2. Extract:
#### o First row
#### o Last column
#### o Diagonal elements
#### o Submatrix (center 3×3)
#### 3. Replace all even numbers with zero
#### 4. Count number of odd elements 

In [56]:
#1. 
arr_5x5 = np.arange(1, 26).reshape(5, 5)
print("Original 5x5 Matrix:\n", arr_5x5)
#2a
print("\nFirst row:", arr_5x5[0, :])
#2b
print("Last column:", arr_5x5[:, -1])
#2c
print("Diagonal elements:", np.diag(arr_5x5))
#2d
print("Center 3x3 Submatrix:\n", arr_5x5[1:4, 1:4])

#3. 
arr_modified = np.where(arr_5x5 % 2 == 0, 0, arr_5x5)
print("\nMatrix with evens replaced by zero:\n", arr_modified)

#4. 
odd_count = np.sum(arr_5x5 % 2 != 0)
print("Total number of odd elements:", odd_count)

Original 5x5 Matrix:
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

First row: [1 2 3 4 5]
Last column: [ 5 10 15 20 25]
Diagonal elements: [ 1  7 13 19 25]
Center 3x3 Submatrix:
 [[ 7  8  9]
 [12 13 14]
 [17 18 19]]

Matrix with evens replaced by zero:
 [[ 1  0  3  0  5]
 [ 0  7  0  9  0]
 [11  0 13  0 15]
 [ 0 17  0 19  0]
 [21  0 23  0 25]]
Total number of odd elements: 13


#### 23.Write a program to:
#### 1. Create an array of integers
#### 2. Filter elements greater than a given value
#### 3. Replace negative values with zero
#### 4. Count number of filtered elements
#### 5. Display results

In [58]:
#1. int_arr = np.array([-5, 10, -2, 15, 8, -9, 20])
threshold = int(input("Enter threshold value to filter elements greater than: "))
#2. 
filtered_elements = int_arr[int_arr > threshold]
print("\nElements greater than", threshold, ":", filtered_elements)
#4. 
print("Count of filtered elements:", len(filtered_elements))
#3. 
replaced_arr = np.where(int_arr < 0, 0, int_arr)
#5. 
print("Array after replacing negatives with zero:\n", replaced_arr)

Enter threshold value to filter elements greater than:  5



Elements greater than 5 : [10 15  8 20]
Count of filtered elements: 4
Array after replacing negatives with zero:
 [ 0 10  0 15  8  0 20]


#### 24.A company stores monthly sales data in a NumPy array. Write a program to:
#### 1. Create a 2-D array with months and sales(user inputs)
#### 2. Calculate total yearly sales
#### 3. Find month with highest and lowest sales
#### 4. Compute average monthly sales
#### 5. Identify months with below-average sales

In [60]:
#1. 
months = ["Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"]
sales_list = []
print("Enter sales data for 12 months:")
for month in months:
    sales = float(input(f"{month} Sales: "))
    sales_list.append(sales)
sales_data = np.array([months, sales_list])
sales_values = sales_data[1, :].astype(float)

#2. 
total_sales = sales_values.sum()
print("\nTotal Yearly Sales:", total_sales)

#3. 
max_index = sales_values.argmax()
min_index = sales_values.argmin()
print(f"Month with Highest Sales: {months[max_index]} ({sales_values[max_index]})")
print(f"Month with Lowest Sales: {months[min_index]} ({sales_values[min_index]})")

#4. 
avg_sales = sales_values.mean()
print("Average Monthly Sales:", round(avg_sales, 2))

#5. 
below_avg_indices = np.where(sales_values < avg_sales)[0]
below_avg_months = [months[i] for i in below_avg_indices]
print("Months with below-average sales:", below_avg_months)

Enter sales data for 12 months:


Jan Sales:  1000
Feb Sales:  1500
Mar Sales:  1200
Apr Sales:  1800
May Sales:  2000
Jun Sales:  2500
Jul Sales:  2200
Aug Sales:  2100
Sep Sales:  1900
Oct Sales:  1600
Nov Sales:  2800
Dec Sales:  3000



Total Yearly Sales: 23600.0
Month with Highest Sales: Dec (3000.0)
Month with Lowest Sales: Jan (1000.0)
Average Monthly Sales: 1966.67
Months with below-average sales: ['Jan', 'Feb', 'Mar', 'Apr', 'Sep', 'Oct']
